### ISSUE TITLE
Hash parameter filtering does not work

### ISSUE THREAD

**Issue by dotpointer** [Neovici/cosmoz-omnitable-treenode-column#25]
Using hash parameter to filter does not work with this column. The filter gets applied when selected, but does not get set when page is reloaded.

**Comment by dotpointer** [comment]
Tested locally with updated components, seems to work as it should. Want to test, @fredrikbernholm ? Test environment needs to have components updated, tested on alpha and it was not yet available there.

**Comment by nomego** [comment]
Fixed @fredrikbernholm ?

**Comment by fredrikbernholm** [comment]
Not sure how to test this. What is "hash parameter" and how should the filtering behave?

**Comment by nomego** [comment]
This seems to be an issue between you @fredrikbernholm and @dotpointer so I'm not sure what the perceived issue was to begin with. Listen with Robert (and read his comment above) or close this issue.

**Comment by dotpointer** [comment]
@nomego @fredrikbernholm 

By hash parameter I meant the URL parameter connected to the table filter.

The issue initially was that the parameter in the URL to filter on the node column in the table refused to work. The parameter in the URL got set when the column filter was changed, but then when the page was reloaded with Ctrl+R, then the parameter was ignored.

This became an issue when links from the statistics into a table view with node columns was requested, since it was not possible to pass the node column filter setting to the linked view. The issue was RM 19353 and the statistic and following view was Invoices for accounting according to the issue if I get it right.

The problem was solved by https://github.com/Neovici/cosmoz-omnitable-treenode-column/pull/28.

**Comment by fredrikbernholm** [comment]
OK, seems to work, so closing this.
