### ISSUE TITLE
Make current selection text read only

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable-treenode-column#6]
When a node is selected, user should be forced to press the "X" to clear, and not be able to remove the text in the input.

(Reported on behalf of @SimonThunborg of @Neovici/uiux )

**Comment by programmer4web** [comment]
paper-autocomplete does not have readonly as property, the iron-input inside is not accessible so an pull-request must be done with this.

**Comment by nomego** [comment]
Yes, please do a PR.
I've added you as a collaborator on our fork (we are not using it ATM, we are using upstream).
Please create a branch there (off of upstream master) and the PR, thanks.

**Comment by programmer4web** [comment]
Added the PR: ellipticaljs/paper-autocomplete#95. 
Dependency should be updated when the PR is merged.
