### ISSUE TITLE
Search on clear

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable-treenode-column#7]
When selection is cleared, no suggestions appear.
User needs to blur the input and re-focus it, which should not be needed.

(Reported on behalf of @SimonThunborg of @Neovici/uiux)

**Comment by nomego** [comment]
Might need the same kind of workaround as paper-autocomplete-chips, see https://github.com/Neovici/paper-autocomplete-chips/blob/master/paper-autocomplete-chips.html#L298

**Comment by programmer4web** [comment]
I'm not able to replicate this, suggestions appear after x is pressed and also if I backspace all the text in the Node paper-autocomplete. Please provide more info.  tested on Chrome 61.0.3 and Firefox 54.

**Comment by nomego** [comment]
Haven't checked references issue/PR yet, but ask @megheaiulian to show you this in the FE otherwise in case there's something only happening there.
